### ISSUE TITLE
No effect on the game in MAME 0.272

### ISSUE THREAD

**Issue by aaciii** [AaronBPaden/defenderlr#6]
With MAME 0.272 I can't seem to get this to have any in-game effect. The plugin is enabled, can see it in the MAME plugins config menu, but it just doesn't seem to do anything. I've tried re-mapping the left/right buttons from defaults (left/right arrows and/or keypad 4 and 6) but nothing at all happens when pressing left/right in the game.   Tried a "clean" install of MAME with only the single defender rom, and no other changes to stock files - same result.

**Comment by aaciii** [comment]
Update....   IT WORKS if mame is launched (including the rom name) from the command line!    It seems to be only if the game is selected from the MAME internal GUI that the script doesn't work.

e.g. 

mame defender 

works, including the plugin.   Tried this on several mame installations.

**Comment by aaciii** [comment]
It seems that emu.romname() == "___empty" if mame is started with no romname on the command line,  This seems to kill the script (it doesn't reinitialize when a ROM is chosen from the UI), so it doesn't kick in / recover once the Defender or Stargate rom is selected and launched).

**Comment by AaronBPaden** [comment]
That's interesting info, thanks. I admit I always launch games through the CLI, with a script to pipe a romlist through the fzf fuzzy finder if I want to search.

I never run things through the UI, so I'm not sure if this is a regression or not. Could be a bug in MAME, or I could be using the API incorrectly. That last one would not surprise me. :) I'll try and make some time to investigate this weekend.

**Comment by aaciii** [comment]
Posted a fix (PR).  It’s a “bug” (sorta) in your code unfortunately.   If the romname isn’t defender or stargate, you unregister the plugin.  That’s a problem for the MAME UI which runs with romname “___empty” until a game is selected.  Your code kills itself (un-registers) before a game is selected.


________________________________

**Comment by AaronBPaden** [comment]
Thanks, closing with #7
